### ISSUE TITLE
100% fan speed when PC wakes up

### ISSUE THREAD

**Issue by massatt212** [Samsagax/hhfc#11]
[hhfc.log](https://github.com/Samsagax/hhfc/files/11995760/hhfc.log)

sudo nano /etc/systemd/system/hhfc-resume.service

[Unit]
Description=Restart hhfc after suspend
After=suspend.target

[Service]
Type=simple
ExecStart=/usr/bin/systemctl restart hhfc.service

[Install]
WantedBy=suspend.target

systemctl enable hhfc-resume.service

This seems to help

**Comment by massatt212** [comment]
sudo nano /etc/systemd/system/hhfc-resume.service

[Unit]
Description=Restart hhfc after Suspend
After=suspend.target

[Service]
Type=simple
ExecStart=/usr/bin/systemctl restart hhfc.service

[Install]
WantedBy=suspend.target

systemctl enable hhfc-resume.service

This seems to help

**Comment by Samsagax** [comment]
Added workaround here
https://github.com/Samsagax/hhfc/commit/88924673a2acce3046a5ee0b71760a84b0c25fd7
