### ISSUE TITLE
Cannot be installed because python-yaml is missing on YAY

### ISSUE THREAD

**Issue by danyi** [Samsagax/hhfc#7]
![59AL K)VW$059T_$(ALY_SP](https://user-images.githubusercontent.com/1498746/208676629-e7421dd0-66b1-4011-a348-6bdc19e2396a.png)

**Comment by Samsagax** [comment]
Should be fixed now. Apparently `yay` doesn't resolve `python-pyyaml` to `python-yaml` package in `[community]`
